version: '3.8'
services:
  APIgateway:
    image: apigateway
    networks:
      - map_inno_default
    ports:
      - 8000:8000
    container_name: APIgateway
  
  auth:
    image: auth
    networks:
      - map_inno_default
    ports:
      - 3003:3003
    container_name: auth

  item:
    image: item
    networks:
      - map_inno_default
    ports:
      - 3001:3001
    container_name: item

  order:
    image: order
    networks:
      - map_inno_default
    ports:
      - 3002:3002
    container_name: order

  mongodb:
    image: mongo
    networks:
      - map_inno_default
    ports:
      - 27017:27017
    container_name: mongodb
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
networks:
  map_inno_default:
    driver: bridge